//! Office 편집 CLI의 catalog·capabilities·help 공유 명령 정의.

use super::{spec, Category, CommandSpec, Visibility};

#[allow(dead_code)]
#[derive(Clone, Copy, Debug)]
pub(crate) struct OfficeCommandSpec {
    pub(crate) command: CommandSpec,
    pub(crate) usage: &'static str,
    pub(crate) summary: &'static str,
    pub(crate) details: &'static [&'static str],
}

impl OfficeCommandSpec {
    /// 사용법에 선언한 옵션을 등장 순서대로 한 번씩 노출한다.
    #[allow(dead_code)]
    pub(crate) fn flags(self) -> Vec<&'static str> {
        let mut flags = Vec::new();
        for token in self
            .usage
            .split(|ch: char| !ch.is_ascii_alphanumeric() && ch != '-')
        {
            if (token.starts_with("--") || token == "-o") && !flags.contains(&token) {
                flags.push(token);
            }
        }
        flags
    }
}

const fn office_spec(
    name: &'static str,
    category: Category,
    usage: &'static str,
    summary: &'static str,
    details: &'static [&'static str],
) -> OfficeCommandSpec {
    OfficeCommandSpec {
        // Office 명령은 자체 JSON을 출력한다. upstream --json 봉투·batch·MCP
        // dispatch에 연결하지 않은 계약은 자기서술에서 약속하지 않는다.
        command: spec(
            name,
            category,
            Visibility::Public,
            None,
            false,
            false,
            false,
        ),
        usage,
        summary,
        details,
    }
}

pub(crate) const COMMANDS: &[OfficeCommandSpec] = &[
    office_spec(
        "create-hwp",
        Category::Edit,
        "create-hwp --text <텍스트>|--text-file <파일> -o <출력.hwp> [--template <파일.hwp|파일.hwpx>]",
        "새 binary HWP 생성 (빈 HWP 또는 템플릿 기반)",
        &[],
    ),
    office_spec(
        "replace-text",
        Category::Edit,
        "replace-text <파일.hwp> --old <검색어> --new <대체문구> -o <출력.hwp> [--all] [--case-sensitive]",
        "binary HWP 본문/표/글상자 텍스트 치환 후 저장",
        &[],
    ),
    office_spec(
        "list-fields",
        Category::Query,
        "list-fields <파일.hwp>",
        "HWP 누름틀/셀 필드 목록을 JSON으로 출력",
        &[],
    ),
    office_spec(
        "insert-clickhere-field",
        Category::Edit,
        "insert-clickhere-field <파일.hwp> --section N --para N [--ctrl N (--cell N|--textbox) [--cell-para N|--textbox-para N] | --cell-path JSON --ctrl N [--textbox-para N]] --offset N --name <필드명> [--guide <안내문>] [--memo <메모>] [--value <초기값>] -o <출력.hwp>",
        "본문/표 셀/글상자 지정 위치에 이름 있는 HWP 누름틀 필드를 생성 후 저장",
        &[],
    ),
    office_spec(
        "get-field-info",
        Category::Query,
        "get-field-info <파일.hwp> --section N --para N [--ctrl N (--cell N|--textbox) [--cell-para N|--textbox-para N]] --offset N",
        "본문/표 셀/글상자 지정 위치의 HWP 누름틀 필드 정보를 JSON으로 출력",
        &[],
    ),
    office_spec(
        "remove-field",
        Category::Edit,
        "remove-field <파일.hwp> --section N --para N [--ctrl N (--cell N|--textbox) [--cell-para N|--textbox-para N]] --offset N -o <출력.hwp>",
        "본문/표 셀/글상자 지정 위치의 HWP 누름틀 필드를 제거하고 텍스트는 유지",
        &[],
    ),
    office_spec(
        "set-field",
        Category::Edit,
        "set-field <파일.hwp> --name <필드명> --value <값> -o <출력.hwp>",
        "이름이 있는 HWP 필드 값을 설정 후 저장",
        &[],
    ),
    office_spec(
        "list-forms",
        Category::Query,
        "list-forms <파일.hwp>",
        "HWP 양식 개체 목록을 이름/위치 JSON으로 출력",
        &[],
    ),
    office_spec(
        "list-objects",
        Category::Query,
        "list-objects <파일.hwp>",
        "본문/표 셀 내부 그림·도형·글상자 객체 목록을 JSON으로 조회",
        &[],
    ),
    office_spec(
        "create-form",
        Category::Edit,
        "create-form <파일.hwp> --section N --para N [--cell-path <JSON>|--table-ctrl N --row R --col C [--cell-para N]] --offset N --form-type checkbox|radio|edit|button|combo --name <이름> [--caption <캡션>] [--text <텍스트>] [--value N] [--width N] [--height N] -o <출력.hwp>",
        "본문 또는 표 셀/글상자 내부 지정 위치에 HWP 양식 개체를 생성 후 저장",
        &[],
    ),
    office_spec(
        "get-form",
        Category::Query,
        "get-form <파일.hwp> --section N --para N [--cell-path <JSON>|--table-ctrl N --row R --col C [--cell-para N]] --ctrl N",
        "HWP 양식 개체 정보를 JSON으로 출력",
        &[],
    ),
    office_spec(
        "set-form",
        Category::Edit,
        "set-form <파일.hwp> --section N --para N [--cell-path <JSON>|--table-ctrl N --row R --col C [--cell-para N]] --ctrl N --json <값JSON> -o <출력.hwp>",
        "HWP 양식 개체의 value/text/caption 값을 설정 후 저장",
        &[],
    ),
    office_spec(
        "delete-form",
        Category::Edit,
        "delete-form <파일.hwp> --section N --para N [--cell-path <JSON>|--table-ctrl N --row R --col C [--cell-para N]] --ctrl N -o <출력.hwp>",
        "HWP 양식 개체를 삭제 후 저장",
        &[],
    ),
    office_spec(
        "extract-structure",
        Category::Query,
        "extract-structure <파일.hwp>",
        "문단/표/셀 위치를 JSON으로 추출",
        &[],
    ),
    office_spec(
        "insert-text",
        Category::Edit,
        "insert-text <파일.hwp> --section N --para N --offset N --text <텍스트> -o <출력.hwp>",
        "본문 문단의 지정 문자 오프셋에 텍스트를 삽입",
        &[],
    ),
    office_spec(
        "delete-text",
        Category::Edit,
        "delete-text <파일.hwp> --section N --para N --offset N --count N -o <출력.hwp>",
        "본문 문단의 지정 문자 범위를 삭제",
        &[],
    ),
    office_spec(
        "set-paragraph",
        Category::Edit,
        "set-paragraph <파일.hwp> --section N --para N --text <텍스트> -o <출력.hwp>",
        "지정 문단 텍스트를 직접 교체",
        &[],
    ),
    office_spec(
        "insert-paragraph",
        Category::Edit,
        "insert-paragraph <파일.hwp> --section N --para N [--text <텍스트>] -o <출력.hwp>",
        "지정 위치에 본문 문단을 삽입",
        &[],
    ),
    office_spec(
        "copy-paragraph",
        Category::Edit,
        "copy-paragraph <파일.hwp> --section N --para N [--before|--after] -o <출력.hwp>",
        "지정 본문 문단을 텍스트와 서식까지 복제",
        &[],
    ),
    office_spec(
        "copy-paragraph-range",
        Category::Edit,
        "copy-paragraph-range <파일.hwp> --section N --start N --end N [--before|--after] [--replace OLD NEW]... -o <출력.hwp>",
        "지정 본문 문단 범위를 같은 순서로 복제",
        &[],
    ),
    office_spec(
        "split-paragraph",
        Category::Edit,
        "split-paragraph <파일.hwp> --section N --para N --offset N -o <출력.hwp>",
        "본문 문단을 문자 오프셋에서 분할",
        &[],
    ),
    office_spec(
        "merge-paragraph",
        Category::Edit,
        "merge-paragraph <파일.hwp> --section N --para N -o <출력.hwp>",
        "지정 본문 문단을 이전 문단에 병합",
        &[],
    ),
    office_spec(
        "delete-paragraph",
        Category::Edit,
        "delete-paragraph <파일.hwp> --section N --para N -o <출력.hwp>",
        "본문 문단을 삭제",
        &[],
    ),
    office_spec(
        "insert-page-break",
        Category::Edit,
        "insert-page-break <파일.hwp> --section N --para N --offset N -o <출력.hwp>",
        "지정 위치에 쪽 나누기를 삽입",
        &[],
    ),
    office_spec(
        "insert-column-break",
        Category::Edit,
        "insert-column-break <파일.hwp> --section N --para N --offset N -o <출력.hwp>",
        "지정 위치에 단 나누기를 삽입",
        &[],
    ),
    office_spec(
        "set-column-def",
        Category::Edit,
        "set-column-def <파일.hwp> --section N --count N [--type normal|distribute|parallel] [--spacing HWPUNIT] [--same-width|--variable-width] -o <출력.hwp>",
        "구역 다단 설정을 변경",
        &[],
    ),
    office_spec(
        "insert-new-number",
        Category::Edit,
        "insert-new-number <파일.hwp> --section N --para N --offset N --start N -o <출력.hwp>",
        "지정 문단 위치부터 쪽 번호를 새 번호로 시작",
        &[],
    ),
    office_spec(
        "get-page-hide",
        Category::Query,
        "get-page-hide <파일.hwp> --section N --para N",
        "문단의 쪽 감추기(PageHide) 상태를 JSON으로 조회",
        &[],
    ),
    office_spec(
        "set-page-hide",
        Category::Edit,
        "set-page-hide <파일.hwp> --section N --para N [--hide-header] [--hide-footer] [--hide-master-page] [--hide-border] [--hide-fill] [--hide-page-num] -o <출력.hwp>",
        "문단의 쪽 감추기(PageHide) 플래그를 설정. 플래그가 없으면 기존 PageHide 제거",
        &[],
    ),
    office_spec(
        "list-bookmarks",
        Category::Query,
        "list-bookmarks <파일.hwp>",
        "문서 내 책갈피 목록을 JSON으로 조회",
        &[],
    ),
    office_spec(
        "add-bookmark",
        Category::Edit,
        "add-bookmark <파일.hwp> --section N --para N --offset N --name <이름> -o <출력.hwp>",
        "본문 위치에 책갈피를 추가",
        &[],
    ),
    office_spec(
        "rename-bookmark",
        Category::Edit,
        "rename-bookmark <파일.hwp> --section N --para N --ctrl N --name <새이름> -o <출력.hwp>",
        "책갈피 이름을 변경",
        &[],
    ),
    office_spec(
        "delete-bookmark",
        Category::Edit,
        "delete-bookmark <파일.hwp> --section N --para N --ctrl N -o <출력.hwp>",
        "책갈피 컨트롤을 삭제",
        &[],
    ),
    office_spec(
        "create-footnote",
        Category::Edit,
        "create-footnote <파일.hwp> --section N --para N --offset N [--text <텍스트>|--text-file <파일>] -o <출력.hwp>",
        "지정 위치에 각주를 생성하고 선택적으로 내용을 입력",
        &[],
    ),
    office_spec(
        "create-endnote",
        Category::Edit,
        "create-endnote <파일.hwp> --section N --para N --offset N [--text <텍스트>|--text-file <파일>] -o <출력.hwp>",
        "지정 위치에 미주를 생성하고 선택적으로 내용을 입력",
        &[],
    ),
    office_spec(
        "get-footnote",
        Category::Query,
        "get-footnote <파일.hwp> --section N --para N --ctrl N",
        "각주/미주 본문 정보를 JSON으로 조회",
        &[],
    ),
    office_spec(
        "insert-footnote-text",
        Category::Edit,
        "insert-footnote-text <파일.hwp> --section N --para N --ctrl N --note-para N --offset N --text <텍스트> -o <출력.hwp>",
        "각주/미주 문단에 텍스트를 삽입",
        &[],
    ),
    office_spec(
        "delete-footnote-text",
        Category::Edit,
        "delete-footnote-text <파일.hwp> --section N --para N --ctrl N --note-para N --offset N --count N -o <출력.hwp>",
        "각주/미주 문단 텍스트 일부를 삭제",
        &[],
    ),
    office_spec(
        "split-footnote-paragraph",
        Category::Edit,
        "split-footnote-paragraph <파일.hwp> --section N --para N --ctrl N --note-para N --offset N -o <출력.hwp>",
        "각주/미주 문단을 분할",
        &[],
    ),
    office_spec(
        "merge-footnote-paragraph",
        Category::Edit,
        "merge-footnote-paragraph <파일.hwp> --section N --para N --ctrl N --note-para N -o <출력.hwp>",
        "각주/미주 문단을 이전 문단과 병합",
        &[],
    ),
    office_spec(
        "delete-footnote",
        Category::Edit,
        "delete-footnote <파일.hwp> --section N --para N --ctrl N -o <출력.hwp>",
        "본문 각주와 각주 본문을 삭제",
        &[],
    ),
    office_spec(
        "create-table",
        Category::Edit,
        "create-table <파일.hwp> --section N --para N --offset N --rows N --cols N -o <출력.hwp>",
        "지정 위치에 HWP 표를 생성",
        &[],
    ),
    office_spec(
        "move-table-to-cell",
        Category::Edit,
        "move-table-to-cell <파일.hwp> --src-para N --src-control N --dst-para N --dst-control N --dst-cell N --dst-cell-para N [--offset N] [-o <출력.hwp>]",
        "본문 표를 지정한 표 셀 안으로 이동",
        &[],
    ),
    office_spec(
        "move-table-from-cell",
        Category::Edit,
        "move-table-from-cell <파일.hwp> --src-para N --src-control N --src-cell N --src-cell-para N [-o <출력.hwp>]",
        "표 셀 안의 중첩 표를 본문으로 이동",
        &[],
    ),
    office_spec(
        "repair-nested-tables",
        Category::Edit,
        "repair-nested-tables <파일.hwp> [-o <출력.hwp>]",
        "중첩 표의 글자처럼 배치 플래그와 instance id를 수리",
        &[],
    ),
    office_spec(
        "lint",
        Category::Diagnostic,
        "lint <파일.hwp>",
        "문서 무결성 검사 결과와 오류·경고 목록을 JSON으로 출력",
        &[],
    ),
    office_spec(
        "copy-table",
        Category::Edit,
        "copy-table <파일.hwp> --section N --para N --ctrl N [--before|--after] [--replace OLD NEW]... -o <출력.hwp>",
        "표 전체를 내용과 서식까지 복제하여 삽입",
        &[],
    ),
    office_spec(
        "delete-table",
        Category::Edit,
        "delete-table <파일.hwp> --section N --para N --ctrl N -o <출력.hwp>",
        "독립 표 문단과 바로 뒤 빈 문단을 삭제",
        &[],
    ),
    office_spec(
        "set-cell-text",
        Category::Edit,
        "set-cell-text <파일.hwp> --para N (--ctrl N (--cell N|--row N --col N)|--cell-path <JSON>) [--cell-para N] --text <텍스트> -o <출력.hwp>",
        "표 셀 문단 텍스트를 직접 교체",
        &["* --cell-path 는 표 안의 표(중첩 표) 셀까지 지정한다: [[표ctrl,셀,셀문단],[안쪽표ctrl,셀,셀문단]]"],
    ),
    office_spec(
        "insert-cell-text",
        Category::Edit,
        "insert-cell-text <파일.hwp> --para N [--ctrl N (--cell N|--row N --col N) [--cell-para N] | --cell-path <JSON>] --offset N --text <텍스트> -o <출력.hwp>",
        "표 셀 문단의 지정 문자 오프셋에 텍스트를 삽입",
        &[],
    ),
    office_spec(
        "delete-cell-text",
        Category::Edit,
        "delete-cell-text <파일.hwp> --para N [--ctrl N (--cell N|--row N --col N) [--cell-para N] | --cell-path <JSON>] --offset N --count N -o <출력.hwp>",
        "표 셀 문단의 지정 문자 범위를 삭제",
        &[],
    ),
    office_spec(
        "insert-cell-paragraph",
        Category::Edit,
        "insert-cell-paragraph <파일.hwp> --para N --ctrl N (--cell N|--row N --col N) --cell-para N [--text <텍스트>] -o <출력.hwp>",
        "표 셀 내부의 지정 위치에 새 문단을 삽입",
        &[],
    ),
    office_spec(
        "delete-cell-paragraph",
        Category::Edit,
        "delete-cell-paragraph <파일.hwp> --para N --ctrl N (--cell N|--row N --col N) --cell-para N -o <출력.hwp>",
        "표 셀 내부 문단을 삭제",
        &[],
    ),
    office_spec(
        "move-cell-paragraphs",
        Category::Edit,
        "move-cell-paragraphs <파일.hwp> --para N --ctrl N --from-row R --from-col C --start N --end N --to-row R --to-col C [--at N] -o <출력.hwp>",
        "표 셀 문단 범위를 다른 셀로 이동",
        &[],
    ),
    office_spec(
        "split-cell-paragraph",
        Category::Edit,
        "split-cell-paragraph <파일.hwp> --para N [--ctrl N (--cell N|--row N --col N) [--cell-para N] | --cell-path <JSON>] --offset N -o <출력.hwp>",
        "표 셀 내부 문단을 문자 오프셋에서 분할",
        &[],
    ),
    office_spec(
        "merge-cell-paragraph",
        Category::Edit,
        "merge-cell-paragraph <파일.hwp> --para N [--ctrl N (--cell N|--row N --col N) --cell-para N | --cell-path <JSON>] -o <출력.hwp>",
        "표 셀 내부 문단을 이전 셀 문단에 병합",
        &[],
    ),
    office_spec(
        "set-cell-field",
        Category::Edit,
        "set-cell-field <파일.hwp> --para N --ctrl N (--cell N|--row N --col N) --name <필드명> -o <출력.hwp>",
        "표 셀을 이름 있는 HWP 셀 필드로 지정",
        &[],
    ),
    office_spec(
        "clear-cell-field",
        Category::Edit,
        "clear-cell-field <파일.hwp> --para N --ctrl N (--cell N|--row N --col N) -o <출력.hwp>",
        "표 셀의 HWP 셀 필드 이름을 제거하고 텍스트는 유지",
        &[],
    ),
    office_spec(
        "insert-table-row",
        Category::Edit,
        "insert-table-row <파일.hwp> --section N --para N --ctrl N --row N [--above|--below] -o <출력.hwp>",
        "표 행을 삽입",
        &[],
    ),
    office_spec(
        "copy-table-row",
        Category::Edit,
        "copy-table-row <파일.hwp> --section N --para N --ctrl N --row N [--above|--below] [--replace OLD NEW]... -o <출력.hwp>",
        "표 행을 내용과 서식까지 복제하여 삽입",
        &[],
    ),
    office_spec(
        "delete-table-row",
        Category::Edit,
        "delete-table-row <파일.hwp> --section N --para N --ctrl N --row N -o <출력.hwp>",
        "표 행을 삭제",
        &[],
    ),
    office_spec(
        "insert-table-column",
        Category::Edit,
        "insert-table-column <파일.hwp> --section N --para N --ctrl N --col N [--left|--right] -o <출력.hwp>",
        "표 열을 삽입",
        &[],
    ),
    office_spec(
        "copy-table-column",
        Category::Edit,
        "copy-table-column <파일.hwp> --section N --para N --ctrl N --col N [--left|--right] [--replace OLD NEW]... -o <출력.hwp>",
        "표 열을 내용과 서식까지 복제하여 삽입",
        &[],
    ),
    office_spec(
        "delete-table-column",
        Category::Edit,
        "delete-table-column <파일.hwp> --section N --para N --ctrl N --col N -o <출력.hwp>",
        "표 열을 삭제",
        &[],
    ),
    office_spec(
        "merge-table-cells",
        Category::Edit,
        "merge-table-cells <파일.hwp> --section N --para N --ctrl N --start-row N --start-col N --end-row N --end-col N -o <출력.hwp>",
        "표 셀 범위를 병합",
        &[],
    ),
    office_spec(
        "split-table-cell",
        Category::Edit,
        "split-table-cell <파일.hwp> --section N --para N --ctrl N --row N --col N -o <출력.hwp>",
        "병합된 표 셀을 분할",
        &[],
    ),
    office_spec(
        "get-cell-properties",
        Category::Query,
        "get-cell-properties <파일.hwp> --section N --para N --ctrl N --cell N",
        "표 셀 속성을 JSON으로 조회",
        &[],
    ),
    office_spec(
        "get-cell-text",
        Category::Query,
        "get-cell-text <파일.hwp> --para N [--ctrl N --cell N | --cell-path <JSON>]",
        "셀 안 문단의 글자 수와 텍스트를 조회 (중첩 표 포함)",
        &["* 편집 명령의 --offset/--count 를 눈대중으로 넘기면 옆 문단이 잘린다.", "먼저 이 명령으로 문단별 실제 길이를 확인할 것"],
    ),
    office_spec(
        "set-cell-properties",
        Category::Edit,
        "set-cell-properties <파일.hwp> --section N --para N --ctrl N --cell N --json <속성JSON> -o <출력.hwp>",
        "표 셀 폭/높이/패딩/정렬/보호/테두리/채우기 속성을 직접 수정",
        &[],
    ),
    office_spec(
        "get-table-properties",
        Category::Query,
        "get-table-properties <파일.hwp> --section N --para N --ctrl N",
        "표 속성을 JSON으로 조회",
        &[],
    ),
    office_spec(
        "set-table-properties",
        Category::Edit,
        "set-table-properties <파일.hwp> --section N --para N --ctrl N --json <속성JSON> -o <출력.hwp>",
        "표 패딩/반복 머리/배치/테두리/채우기 속성을 직접 수정",
        &[],
    ),
    office_spec(
        "resize-table-cells",
        Category::Edit,
        "resize-table-cells <파일.hwp> --section N --para N [--cell-path <JSON>|--ctrl N] --json <변경배열JSON> -o <출력.hwp>",
        "여러 표 셀의 폭/높이를 델타 값으로 조절",
        &[],
    ),
    office_spec(
        "set-table-column-widths",
        Category::Edit,
        "set-table-column-widths <파일.hwp> --section N --para N --ctrl N --widths w1,w2,... -o <출력.hwp>",
        "표 열 너비를 지정한 값으로 설정",
        &[],
    ),
    office_spec(
        "apply-table-style",
        Category::Edit,
        "apply-table-style <파일.hwp> --section N --para N --ctrl N [--head-fill #d9d9d9] [--font-size 1200] [--head-height 2232] [--body-height 2882] -o <출력.hwp>",
        "표에 심사 문서용 「집 서식」을 한 번에 적용 (머리행 음영+이중선, 정렬, 12pt, 행 높이)",
        &[],
    ),
    office_spec(
        "get-char-properties",
        Category::Query,
        "get-char-properties <파일.hwp> --section N --para N --offset N",
        "본문 글자 속성을 JSON으로 조회",
        &[],
    ),
    office_spec(
        "set-char-format",
        Category::Edit,
        "set-char-format <파일.hwp> --section N --para N --start N --end N --json <서식JSON> -o <출력.hwp>",
        "본문 글자 범위 서식을 직접 수정",
        &[],
    ),
    office_spec(
        "get-para-properties",
        Category::Query,
        "get-para-properties <파일.hwp> --section N --para N",
        "본문 문단 속성을 JSON으로 조회",
        &[],
    ),
    office_spec(
        "set-para-format",
        Category::Edit,
        "set-para-format <파일.hwp> --section N --para N --json <서식JSON> -o <출력.hwp>",
        "본문 문단 서식을 직접 수정",
        &[],
    ),
    office_spec(
        "list-styles",
        Category::Query,
        "list-styles <파일.hwp>",
        "문서 스타일 목록을 JSON으로 조회",
        &[],
    ),
    office_spec(
        "apply-style",
        Category::Edit,
        "apply-style <파일.hwp> --section N --para N (--style-id N|--style-name <이름>) -o <출력.hwp>",
        "본문 문단에 문서 스타일을 적용",
        &[],
    ),
    office_spec(
        "apply-cell-style",
        Category::Edit,
        "apply-cell-style <파일.hwp> --section N --para N --ctrl N (--cell N|--row R --col C) [--cell-para N] (--style-id N|--style-name <이름>) -o <출력.hwp>",
        "표 셀 내부 문단에 문서 스타일을 적용",
        &[],
    ),
    office_spec(
        "get-cell-char-properties",
        Category::Query,
        "get-cell-char-properties <파일.hwp> --section N --para N --ctrl N (--cell N|--row R --col C) [--cell-para N] --offset N",
        "셀 내부 글자 속성을 JSON으로 조회",
        &[],
    ),
    office_spec(
        "set-cell-char-format",
        Category::Edit,
        "set-cell-char-format <파일.hwp> --section N --para N (--ctrl N (--cell N|--row R --col C) [--cell-para N] | --cell-path <JSON>) --start N --end N --json <서식JSON> -o <출력.hwp>",
        "셀 내부 글자 범위 서식을 직접 수정",
        &[],
    ),
    office_spec(
        "get-cell-para-properties",
        Category::Query,
        "get-cell-para-properties <파일.hwp> --section N --para N --ctrl N (--cell N|--row R --col C) [--cell-para N]",
        "셀 내부 문단 속성을 JSON으로 조회",
        &[],
    ),
    office_spec(
        "set-cell-para-format",
        Category::Edit,
        "set-cell-para-format <파일.hwp> --section N --para N --ctrl N (--cell N|--row R --col C) [--cell-para N] --json <서식JSON> -o <출력.hwp>",
        "셀 내부 문단 서식을 직접 수정",
        &[],
    ),
    office_spec(
        "get-page-def",
        Category::Query,
        "get-page-def <파일.hwp> --section N",
        "용지 크기/여백 설정을 JSON으로 조회",
        &[],
    ),
    office_spec(
        "set-page-def",
        Category::Edit,
        "set-page-def <파일.hwp> --section N --json <설정JSON> -o <출력.hwp>",
        "용지 크기/여백 설정을 직접 수정",
        &[],
    ),
    office_spec(
        "get-section-def",
        Category::Query,
        "get-section-def <파일.hwp> --section N",
        "구역 번호/숨김/탭 설정을 JSON으로 조회",
        &[],
    ),
    office_spec(
        "set-section-def",
        Category::Edit,
        "set-section-def <파일.hwp> --section N --json <설정JSON> -o <출력.hwp>",
        "구역 번호/숨김/탭 설정을 직접 수정",
        &[],
    ),
    office_spec(
        "get-page-border-fill",
        Category::Query,
        "get-page-border-fill <파일.hwp> --section N",
        "쪽 테두리/배경 설정을 JSON으로 조회",
        &[],
    ),
    office_spec(
        "set-page-border-fill",
        Category::Edit,
        "set-page-border-fill <파일.hwp> --section N --json <설정JSON> -o <출력.hwp>",
        "쪽 테두리/배경 설정을 직접 수정",
        &[],
    ),
    office_spec(
        "insert-picture",
        Category::Edit,
        "insert-picture <파일.hwp> --section N --para N --offset N --image <이미지> --width N --height N [--cell-path <JSON>|--table-ctrl N --row R --col C [--cell-para N]] [--natural-width N --natural-height N] [--inline] -o <출력.hwp>",
        "그림 컨트롤을 삽입",
        &["--natural-width/--natural-height 생략 시 이미지 헤더에서 자동 판독", "--inline  표 셀 안에 글자처럼(인라인) 삽입 — 셀 높이가 그림에 맞춰 늘어난다.", "생략하면 한컴 default 인 표 옆 floating 배치 (셀 밖으로 넘칠 수 있음)"],
    ),
    office_spec(
        "get-picture-properties",
        Category::Query,
        "get-picture-properties <파일.hwp> --section N --para N [--cell-path <JSON>|--table-ctrl N --row R --col C [--cell-para N]] --ctrl N",
        "본문/표 셀 내부 그림 속성을 JSON으로 조회",
        &[],
    ),
    office_spec(
        "set-picture-properties",
        Category::Edit,
        "set-picture-properties <파일.hwp> --section N --para N [--cell-path <JSON>|--table-ctrl N --row R --col C [--cell-para N]] --ctrl N --json <속성JSON> -o <출력.hwp>",
        "본문/표 셀 내부 그림 크기/위치/효과/자르기/캡션 속성을 직접 수정",
        &[],
    ),
    office_spec(
        "delete-picture",
        Category::Edit,
        "delete-picture <파일.hwp> --section N --para N [--cell-path <JSON>|--table-ctrl N --row R --col C [--cell-para N]] --ctrl N -o <출력.hwp>",
        "본문/표 셀 내부 그림 컨트롤 삭제",
        &[],
    ),
    office_spec(
        "create-shape",
        Category::Edit,
        "create-shape <파일.hwp> --section N --para N [--cell-path <JSON>|--table-ctrl N --row R --col C [--cell-para N]] --offset N --width N --height N [--shape-type rectangle|textbox|line|ellipse|polygon|arc] -o <출력.hwp>",
        "본문/표 셀 내부 도형·글상자 컨트롤을 삽입",
        &[],
    ),
    office_spec(
        "set-cell-shape-text",
        Category::Edit,
        "set-cell-shape-text <파일.hwp> --section N --para N [--cell-path <JSON>|--table-ctrl N --row R --col C [--cell-para N]] --ctrl N [--textbox-para N] --text <텍스트> -o <출력.hwp>",
        "표 셀 내부 글상자 텍스트를 직접 수정",
        &[],
    ),
    office_spec(
        "set-cell-shape-char-format",
        Category::Edit,
        "set-cell-shape-char-format <파일.hwp> --section N --para N [--cell-path <JSON>|--table-ctrl N --row R --col C [--cell-para N]] --ctrl N --textbox-para N --start N --end N --json <서식JSON> -o <출력.hwp>",
        "표 셀 내부 글상자 문자 범위 서식을 직접 수정",
        &[],
    ),
    office_spec(
        "set-cell-shape-para-format",
        Category::Edit,
        "set-cell-shape-para-format <파일.hwp> --section N --para N [--cell-path <JSON>|--table-ctrl N --row R --col C [--cell-para N]] --ctrl N --textbox-para N --json <서식JSON> -o <출력.hwp>",
        "표 셀 내부 글상자 문단 서식을 직접 수정",
        &[],
    ),
    office_spec(
        "get-shape-properties",
        Category::Query,
        "get-shape-properties <파일.hwp> --section N --para N --ctrl N",
        "도형 속성을 JSON으로 조회",
        &[],
    ),
    office_spec(
        "set-shape-properties",
        Category::Edit,
        "set-shape-properties <파일.hwp> --section N --para N --ctrl N --json <속성JSON> -o <출력.hwp>",
        "도형 크기/위치/선/채우기/글상자 속성을 직접 수정",
        &[],
    ),
    office_spec(
        "delete-shape",
        Category::Edit,
        "delete-shape <파일.hwp> --section N --para N --ctrl N -o <출력.hwp>",
        "도형 컨트롤 삭제",
        &[],
    ),
    office_spec(
        "change-shape-z-order",
        Category::Edit,
        "change-shape-z-order <파일.hwp> --section N --para N --ctrl N --operation front|back|forward|backward -o <출력.hwp>",
        "도형의 앞/뒤 배치 순서를 변경",
        &[],
    ),
    office_spec(
        "group-shapes",
        Category::Edit,
        "group-shapes <파일.hwp> --section N --targets <대상JSON> -o <출력.hwp>",
        "여러 그림/도형을 하나의 그룹으로 묶기",
        &[],
    ),
    office_spec(
        "ungroup-shape",
        Category::Edit,
        "ungroup-shape <파일.hwp> --section N --para N --ctrl N -o <출력.hwp>",
        "그룹 도형을 한 단계 풀기",
        &[],
    ),
    office_spec(
        "get-header-footer",
        Category::Query,
        "get-header-footer <파일.hwp> --section N --kind header|footer --apply-to both|even|odd",
        "머리말/꼬리말 내용과 위치를 JSON으로 조회",
        &[],
    ),
    office_spec(
        "list-header-footer",
        Category::Query,
        "list-header-footer <파일.hwp> [--section N --kind header|footer --apply-to both|even|odd]",
        "문서의 머리말/꼬리말 목록을 JSON으로 조회",
        &[],
    ),
    office_spec(
        "create-header-footer",
        Category::Edit,
        "create-header-footer <파일.hwp> --section N --kind header|footer --apply-to both|even|odd -o <출력.hwp>",
        "빈 머리말/꼬리말을 생성",
        &[],
    ),
    office_spec(
        "delete-header-footer",
        Category::Edit,
        "delete-header-footer <파일.hwp> --section N --kind header|footer --apply-to both|even|odd -o <출력.hwp>",
        "머리말/꼬리말 컨트롤 삭제",
        &[],
    ),
    office_spec(
        "insert-header-footer-text",
        Category::Edit,
        "insert-header-footer-text <파일.hwp> --section N --kind header|footer --apply-to both|even|odd --hf-para N --offset N --text <텍스트> -o <출력.hwp>",
        "머리말/꼬리말 문단에 텍스트를 삽입",
        &[],
    ),
    office_spec(
        "delete-header-footer-text",
        Category::Edit,
        "delete-header-footer-text <파일.hwp> --section N --kind header|footer --apply-to both|even|odd --hf-para N --offset N --count N -o <출력.hwp>",
        "머리말/꼬리말 문단에서 텍스트를 삭제",
        &[],
    ),
    office_spec(
        "split-header-footer-paragraph",
        Category::Edit,
        "split-header-footer-paragraph <파일.hwp> --section N --kind header|footer --apply-to both|even|odd --hf-para N --offset N -o <출력.hwp>",
        "머리말/꼬리말 문단을 분할",
        &[],
    ),
    office_spec(
        "merge-header-footer-paragraph",
        Category::Edit,
        "merge-header-footer-paragraph <파일.hwp> --section N --kind header|footer --apply-to both|even|odd --hf-para N -o <출력.hwp>",
        "머리말/꼬리말 문단을 이전 문단과 병합",
        &[],
    ),
    office_spec(
        "get-header-footer-para-info",
        Category::Query,
        "get-header-footer-para-info <파일.hwp> --section N --kind header|footer --apply-to both|even|odd --hf-para N",
        "머리말/꼬리말 문단의 텍스트와 문자 수를 JSON으로 조회",
        &[],
    ),
    office_spec(
        "get-header-footer-para-properties",
        Category::Query,
        "get-header-footer-para-properties <파일.hwp> --section N --kind header|footer --apply-to both|even|odd --hf-para N",
        "머리말/꼬리말 문단 서식을 JSON으로 조회",
        &[],
    ),
    office_spec(
        "set-header-footer-para-format",
        Category::Edit,
        "set-header-footer-para-format <파일.hwp> --section N --kind header|footer --apply-to both|even|odd --hf-para N --json <서식JSON> -o <출력.hwp>",
        "머리말/꼬리말 문단 서식을 직접 수정",
        &[],
    ),
    office_spec(
        "insert-header-footer-field",
        Category::Edit,
        "insert-header-footer-field <파일.hwp> --section N --kind header|footer --apply-to both|even|odd --hf-para N --offset N --field page-number|total-pages|filename -o <출력.hwp>",
        "머리말/꼬리말에 쪽번호/총쪽수/파일명 필드를 삽입",
        &[],
    ),
    office_spec(
        "apply-header-footer-template",
        Category::Edit,
        "apply-header-footer-template <파일.hwp> --section N --kind header|footer --apply-to both|even|odd --template N -o <출력.hwp>",
        "기본 머리말/꼬리말 템플릿(0~10)을 적용",
        &[],
    ),
    office_spec(
        "list-master-pages",
        Category::Query,
        "list-master-pages <파일.hwp> --section N",
        "바탕쪽 목록과 텍스트를 JSON으로 조회",
        &[],
    ),
    office_spec(
        "create-master-page",
        Category::Edit,
        "create-master-page <파일.hwp> --section N --apply-to both|even|odd [--text <텍스트>] [--extension] [--overlap] -o <출력.hwp>",
        "바탕쪽을 생성",
        &[],
    ),
    office_spec(
        "set-master-page-text",
        Category::Edit,
        "set-master-page-text <파일.hwp> --section N --master N --para N --text <텍스트> -o <출력.hwp>",
        "바탕쪽 문단 텍스트를 수정",
        &[],
    ),
    office_spec(
        "delete-master-page",
        Category::Edit,
        "delete-master-page <파일.hwp> --section N --master N -o <출력.hwp>",
        "바탕쪽을 삭제",
        &[],
    ),
];
